In [1]:
import pandas as pd
import glob
import numpy as np
import pathlib as pl

### 1) Combine all the pks datasets

In [2]:
PATH_TO_PROCESSED_DATA = pl.Path('../datasets/processed')

cases_basic_table_files = glob.glob('../datasets/raw/police_stats/pks20[0-9][0-9]CasesBasicTable_excel.xlsx')
cases_development_files = glob.glob('../datasets/raw/police_stats/pks20[0-9][0-9]CasesDevelopment_excel.xlsx')
suspects_files = glob.glob('../datasets/raw/police_stats/pks20[0-9][0-9]Suspects_excel.xlsx')
len(cases_basic_table_files), len(cases_development_files), len(suspects_files)

(10, 10, 10)

 - first combine all the disticnt tables from all the years to 3 tables throughout the years

#### 1.11 PKS basic table

In [3]:
df = pd.read_excel(cases_basic_table_files[0], skiprows=8, usecols='B:T', header=None,
              names=["offence or offence category", "recorded cases", "percentage of all cases", "attempts number", "attempts %", "< 20,000 inhabitants", "20,000 up to 100,000 inhabitants", "100,000 up to 500,000 inhabitants", "500,000 and more inhabitants",  "unknown inhabitants", "firearm threatened", "firearm shot", "clearance number", "clearance %", "suspects count", "male suspects", "female suspects", "non-German suspects number", "non-German suspects %"]) # for sure there is a way how to automate the extraction of the names from various rows, but this seems to be easier

df

,offence or offence category,recorded cases,percentage of all cases,attempts number,attempts %,"< 20,000 inhabitants","20,000 up to 100,000 inhabitants","100,000 up to 500,000 inhabitants","500,000 and more inhabitants",unknown inhabitants,firearm threatened,firearm shot,clearance number,clearance %,suspects count,male suspects,female suspects,non-German suspects number,non-German suspects %
0,total offences,6082064.0,100.0,461117.0,7.6,1404723.0,1602590.0,1261205.0,1755141.0,58405.0,4567.0,5018.0,3336398.0,54.9,2149504.0,1597241.0,552263.0,617392.0,28.7
1,offences against life,2962.0,0.0,1658.0,56.0,912.0,932.0,575.0,529.0,14.0,12.0,112.0,2760.0,93.2,3684.0,3083.0,601.0,947.0,25.7
2,murder (sect. 211 PC),664.0,0.0,415.0,62.5,223.0,182.0,119.0,136.0,4.0,5.0,56.0,633.0,95.3,829.0,699.0,130.0,247.0,29.8
3,other types of murder,602.0,0.0,385.0,64.0,201.0,168.0,109.0,120.0,4.0,3.0,54.0,575.0,95.5,740.0,617.0,123.0,227.0,30.7
4,robbery attended with murder,44.0,0.0,21.0,47.7,14.0,10.0,7.0,13.0,0.0,2.0,1.0,41.0,93.2,75.0,68.0,7.0,19.0,25.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1024,environmental offences pursuant to supplementa...,14890.0,0.2,137.0,0.9,6508.0,3465.0,1794.0,3049.0,74.0,0.0,437.0,11215.0,75.3,12030.0,9654.0,2376.0,1858.0,15.4
1025,street crime,1342905.0,22.1,77948.0,5.8,266329.0,350467.0,287668.0,434587.0,3854.0,524.0,1350.0,222012.0,16.5,195751.0,173095.0,22656.0,48851.0,25.0
1026,damage to property by graffiti in total,95160.0,1.6,237.0,0.2,20390.0,24380.0,21477.0,27961.0,952.0,0.0,0.0,17871.0,18.8,9793.0,8591.0,1202.0,847.0,8.6
1027,illegal entry/illegal stay under the Aliens Ac...,135743.0,2.2,2293.0,1.7,31095.0,32487.0,23368.0,48328.0,465.0,0.0,0.0,135516.0,99.8,131458.0,97406.0,34052.0,131000.0,99.7
1028,hightec/computer crime in the narrower sense,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
def combine_pks_tables(fnames: list[str], names: list[str], skiprows: int, usecols: str) -> pd.DataFrame:
    table = pd.DataFrame()

    for i, fname in enumerate(fnames):
        print(fname)
        
        year = 2014 + i
        new_names = [f"{year} {n}" for n in names] 
        df_i = pd.read_excel(fname, skiprows=skiprows, usecols=usecols, header=None,
                  names=new_names)
        
        table = pd.concat([table, df_i], axis=1)
    
    return table

In [8]:
basic_table = combine_pks_tables(cases_basic_table_files, ["offence or offence category", "recorded cases", "percentage of all cases", "attempts number", "attempts %", "< 20,000 inhabitants", "20,000 up to 100,000 inhabitants", "100,000 up to 500,000 inhabitants", "500,000 and more inhabitants",  "unknown inhabitants", "firearm threatened", "firearm shot", "clearance number", "clearance %", "suspects count", "male suspects", "female suspects", "non-German suspects number", "non-German suspects %"], 8, 'B:T')

basic_table.to_csv(PATH_TO_PROCESSED_DATA / 'pks_basic_table.csv')

basic_table.head

../datasets/raw/police_stats\pks2014CasesBasicTable_excel.xlsx
../datasets/raw/police_stats\pks2015CasesBasicTable_excel.xlsx
../datasets/raw/police_stats\pks2016CasesBasicTable_excel.xlsx
../datasets/raw/police_stats\pks2017CasesBasicTable_excel.xlsx
../datasets/raw/police_stats\pks2018CasesBasicTable_excel.xlsx
../datasets/raw/police_stats\pks2019CasesBasicTable_excel.xlsx
../datasets/raw/police_stats\pks2020CasesBasicTable_excel.xlsx
../datasets/raw/police_stats\pks2021CasesBasicTable_excel.xlsx
../datasets/raw/police_stats\pks2022CasesBasicTable_excel.xlsx
../datasets/raw/police_stats\pks2023CasesBasicTable_excel.xlsx

<bound method NDFrame.head of      2014 offence or offence category  2014 recorded cases  \
0                      total offences            6082064.0
1               offences against life               2962.0
2               murder (sect. 211 PC)                664.0
3               other types of murder                602.0
4        robbery attended with murder                 44.0
...                               ...                  ...
1134                              NaN                  NaN
1135                              NaN                  NaN
1136                              NaN                  NaN
1137                              NaN                  NaN
1138                              NaN                  NaN

      2014 percentage of all cases  2014 attempts number  2014 attempts %  \
0                            100.0              461117.0              7.6
1                              0.0                1658.0             56.0
2                              0.0                 415.0             62.5
3                              0.0                 385.0             64.0
4                              0.0                  21.0             47.7
...                            ...                   ...              ...
1134                           NaN                   NaN              NaN
1135                           NaN                   NaN              NaN
1136                           NaN                   NaN              NaN
1137                           NaN                   NaN              NaN
1138                           NaN                   NaN              NaN

      2014 < 20,000 inhabitants  2014 20,000 up to 100,000 inhabitants  \
0                     1404723.0                              1602590.0
1                         912.0                                  932.0
2                         223.0                                  182.0
3                         201.0                                  168.0
4                          14.0                                   10.0
...                         ...                                    ...
1134                        NaN                                    NaN
1135                        NaN                                    NaN
1136                        NaN                                    NaN
1137                        NaN                                    NaN
1138                        NaN                                    NaN

      2014 100,000 up to 500,000 inhabitants  \
0                                  1261205.0
1                                      575.0
2                                      119.0
3                                      109.0
4                                        7.0
...                                      ...
1134                                     NaN
1135                                     NaN
1136                                     NaN
1137                                     NaN
1138                                     NaN

      2014 500,000 and more inhabitants  2014 unknown inhabitants  ...  \
0                             1755141.0                   58405.0  ...
1                                 529.0                      14.0  ...
2                                 136.0                       4.0  ...
3                                 120.0                       4.0  ...
4                                  13.0                       0.0  ...
...                                 ...                       ...  ...
1134                                NaN                       NaN  ...
1135                                NaN                       NaN  ...
1136                                NaN                       NaN  ...
1137                                NaN                       NaN  ...
1138                                NaN                       NaN  ...

      2023 unknown inhabitants  2023 firearm threatened  2023 firearm shot  \
0                     123939.0                   4419.0             4687.0
1                         13.0                      4.0              157.0
2                          8.0                      1.0               53.0
3                          8.0                      0.0               52.0
4                          0.0                      1.0                1.0
...                        ...                      ...                ...
1134                     132.0                      0.0                0.0
1135                    5434.0                      0.0                0.0
1136                     714.0                      0.0                0.0
1137                      72.0                      0.0                0.0
1138                       NaN                      NaN                NaN

      2023 clearance number  2023 clearance %  2023 suspects count  \
0                 3469752.0              58.4            2246767.0
1                    2759.0              89.5               3735.0
2                     650.0              92.3                824.0
3                     625.0                92                764.0
4                      20.0               100                 55.0
...                     ...               ...                  ...
1134                 9701.0              92.9               8849.0
1135               197173.0              91.3             176634.0
1136                18664.0              85.5              18773.0
1137                 7589.0              93.5               6828.0
1138                    NaN               NaN                  NaN

      2023 male suspects  2023 female suspects  \
0              1675541.0              571226.0
1                 3090.0                 645.0
2                  705.0                 119.0
3                  657.0                 107.0
4                   43.0                  12.0
...                  ...                   ...
1134              7171.0                1678.0
1135            156393.0               20241.0
1136             16069.0                2704.0
1137              5483.0                1345.0
1138                 NaN                   NaN

      2023 non-German suspects number 2023 non-German suspects %
0                            923269.0                       41.1
1                              1418.0                         38
2                               355.0                       43.1
3                               313.0                         41
4                                41.0                       74.5
...                               ...                        ...
1134                           1881.0                       21.3
1135                          58798.0                       33.3
1136                           5730.0                       30.5
1137                           1372.0                       20.1
1138                              NaN                        NaN

[1139 rows x 190 columns]>

Note: some of the older datasets do not contain all the data, therefore their ends are filled with NaN values, 
This is not a problem, as these are really niche signal variable subtypes. the important types such as "offences against life", "murder", or "robbery attended with murder" are on the top. These are really the data we need.

#### 1.2 PKS Cases Development

In [6]:
df = pd.read_excel(cases_development_files[0], skiprows=16, usecols='C,D,H', header=None, names=["offence or offence category", "recorded cases", "clearance rate %"])
df

,offence or offence category,recorded cases,clearance rate %
0,total offences,6082064,54.9
1,offences against life,2962,93.2
2,murder (sect. 211 PC),664,95.3
3,other types of murder,602,95.5
4,robbery attended with murder,44,93.2
...,...,...,...
1024,environmental offences pursuant to supplementa...,14890,75.3
1025,street crime,1342905,16.5
1026,damage to property by graffiti in total,95160,18.8
1027,illegal entry/illegal stay under the Aliens Ac...,135743,99.8
1028,hightec/computer crime in the narrower sense,49925,29.3

In [14]:
# for sure there is a way how to automate the extraction of the names from various rows, but this seems to be easier
cases_development_table = combine_pks_tables(cases_basic_table_files, ["offence or offence category", "recorded cases", "clearance rate %"], 16, 'C,D,H')

cases_development_table.to_csv(PATH_TO_PROCESSED_DATA / 'pks_development_table.csv')

cases_development_table.head

../datasets/raw/police_stats\pks2014CasesBasicTable_excel.xlsx
../datasets/raw/police_stats\pks2015CasesBasicTable_excel.xlsx
../datasets/raw/police_stats\pks2016CasesBasicTable_excel.xlsx
../datasets/raw/police_stats\pks2017CasesBasicTable_excel.xlsx
../datasets/raw/police_stats\pks2018CasesBasicTable_excel.xlsx
../datasets/raw/police_stats\pks2019CasesBasicTable_excel.xlsx
../datasets/raw/police_stats\pks2020CasesBasicTable_excel.xlsx
../datasets/raw/police_stats\pks2021CasesBasicTable_excel.xlsx
../datasets/raw/police_stats\pks2022CasesBasicTable_excel.xlsx
../datasets/raw/police_stats\pks2023CasesBasicTable_excel.xlsx

<bound method NDFrame.head of       2014 offence or offence category  2014 recorded cases  \
0                                  7.0                  0.0
1                                 17.0                  0.0
2                                698.0                  0.0
3                                 85.0                  0.0
4                                 80.0                  0.0
...                                ...                  ...
1126                               NaN                  NaN
1127                               NaN                  NaN
1128                               NaN                  NaN
1129                               NaN                  NaN
1130                               NaN                  NaN

      2014 clearance rate %  2015 offence or offence category  \
0                       0.0                               6.0
1                       1.0                              13.0
2                     245.0                             756.0
3                      15.0                             119.0
4                      14.0                              85.0
...                     ...                               ...
1126                    NaN                               NaN
1127                    NaN                               NaN
1128                    NaN                               NaN
1129                    NaN                               NaN
1130                    NaN                               NaN

      2015 recorded cases  2015 clearance rate %  \
0                     0.0                    4.0
1                     0.0                    2.0
2                     0.0                  272.0
3                     0.0                   33.0
4                     0.0                   21.0
...                   ...                    ...
1126                  NaN                    NaN
1127                  NaN                    NaN
1128                  NaN                    NaN
1129                  NaN                    NaN
1130                  NaN                    NaN

      2016 offence or offence category  2016 recorded cases  \
0                                  3.0                  0.0
1                                 24.0                  0.0
2                                686.0                  0.0
3                                138.0                  0.0
4                                102.0                  0.0
...                                ...                  ...
1126                               NaN                  NaN
1127                               NaN                  NaN
1128                               NaN                  NaN
1129                               NaN                  NaN
1130                               NaN                  NaN

      2016 clearance rate %  2017 offence or offence category  ...  \
0                       1.0                               7.0  ...
1                       6.0                              17.0  ...
2                     239.0                             737.0  ...
3                      43.0                             110.0  ...
4                      32.0                              78.0  ...
...                     ...                               ...  ...
1126                    NaN                               NaN  ...
1127                    NaN                               NaN  ...
1128                    NaN                               NaN  ...
1129                    NaN                               NaN  ...
1130                    NaN                               NaN  ...

      2020 clearance rate %  2021 offence or offence category  \
0                       0.0                               1.0
1                       5.0                              20.0
2                     263.0                             786.0
3                      32.0                              83.0
4                      32.0                              80.0
...                     ...                               ...
1126                    NaN                               NaN
1127                    NaN                               NaN
1128                    NaN                               NaN
1129                    NaN                               NaN
1130                    NaN                               NaN

      2021 recorded cases  2021 clearance rate %  \
0                     0.0                    0.0
1                     0.0                    4.0
2                     0.0                  240.0
3                     0.0                   27.0
4                     0.0                   27.0
...                   ...                    ...
1126                  NaN                    NaN
1127                  NaN                    NaN
1128                  NaN                    NaN
1129                  NaN                    NaN
1130                  NaN                    NaN

      2022 offence or offence category  2022 recorded cases  \
0                                    1                  0.0
1                                   24                  0.0
2                                  748                  0.0
3                                   93                  0.0
4                                   92                  0.0
...                                ...                  ...
1126                             42213                  0.7
1127                             11482                  0.2
1128                            214242                  3.8
1129                             21537                  0.4
1130                              9035                  0.2

      2022 clearance rate %  2023 offence or offence category  \
0                         0                               1.0
1                         8                              24.0
2                       270                             703.0
3                        26                              98.0
4                        26                              90.0
...                     ...                               ...
1126                  13278                           10446.0
1127                   4089                          215865.0
1128                  63418                           21841.0
1129                   6301                            8116.0
1130                   3359                               NaN

      2023 recorded cases  2023 clearance rate %
0                0.000017                    0.0
1                0.000404                    5.0
2                0.011834                  245.0
3                0.001650                   36.0
4                0.001515                   34.0
...                   ...                    ...
1126             0.175839                 3724.0
1127             3.633683                61827.0
1128             0.367652                 6415.0
1129             0.136618                 3045.0
1130                  NaN                    NaN

[1131 rows x 30 columns]>

#### 1.3 Suspects

In [12]:
df = pd.read_excel(suspects_files[0], skiprows=9, usecols='B,C,D,O,X', header=None, names=["offence or offence category", "sex", "total suspects number", "children under 21", "adults 21>"])
df

,offence or offence category,sex,total suspects number,children under 21,adults 21>
0,total offences,m %,7.430742e+01,73.020783,7.464900e+01
1,total offences,f %,2.569258e+01,26.979217,2.535100e+01
2,total offences,x %,1.000000e+02,20.978607,7.902139e+01
3,total offences,m,1.597241e+06,329277.000000,1.267964e+06
4,total offences,f,5.522630e+05,121659.000000,4.306040e+05
...,...,...,...,...,...
3085,illegal entry/illegal stay under the Aliens Ac...,f,3.405200e+04,7525.000000,2.652700e+04
3086,illegal entry/illegal stay under the Aliens Ac...,x,1.314580e+05,33110.000000,9.834800e+04
3087,hightec/computer crime in the narrower sense,m,9.106000e+03,1274.000000,7.832000e+03
3088,hightec/computer crime in the narrower sense,f,2.664000e+03,353.000000,2.311000e+03
3089,hightec/computer crime in the narrower sense,x,1.177000e+04,1627.000000,1.014300e+04

In [15]:
suspects_table = combine_pks_tables(suspects_files, ["offence or offence category", "sex", "total suspects number", "children under 21", "adults 21>"], 9, 'B,C,D,O,X')

suspects_table.to_csv(PATH_TO_PROCESSED_DATA / 'pks_suspects_table.csv')

suspects_table.head

../datasets/raw/police_stats\pks2014Suspects_excel.xlsx
../datasets/raw/police_stats\pks2015Suspects_excel.xlsx
../datasets/raw/police_stats\pks2016Suspects_excel.xlsx
../datasets/raw/police_stats\pks2017Suspects_excel.xlsx
../datasets/raw/police_stats\pks2018Suspects_excel.xlsx
../datasets/raw/police_stats\pks2019Suspects_excel.xlsx
../datasets/raw/police_stats\pks2020Suspects_excel.xlsx
../datasets/raw/police_stats\pks2021Suspects_excel.xlsx
../datasets/raw/police_stats\pks2022Suspects_excel.xlsx
../datasets/raw/police_stats\pks2023Suspects_excel.xlsx

<bound method NDFrame.head of      2014 offence or offence category 2014 sex  2014 total suspects number  \
0                      total offences      m %                7.430742e+01
1                      total offences      f %                2.569258e+01
2                      total offences      x %                1.000000e+02
3                      total offences        m                1.597241e+06
4                      total offences        f                5.522630e+05
...                               ...      ...                         ...
3376                              NaN      NaN                         NaN
3377                              NaN      NaN                         NaN
3378                              NaN      NaN                         NaN
3379                              NaN      NaN                         NaN
3380                              NaN      NaN                         NaN

      2014 children under 21  2014 adults 21>  \
0                  73.020783     7.464900e+01
1                  26.979217     2.535100e+01
2                  20.978607     7.902139e+01
3              329277.000000     1.267964e+06
4              121659.000000     4.306040e+05
...                      ...              ...
3376                     NaN              NaN
3377                     NaN              NaN
3378                     NaN              NaN
3379                     NaN              NaN
3380                     NaN              NaN

     2015 offence or offence category 2015 sex  2015 total suspects number  \
0                      total offences        m                   1781388.0
1                      total offences        f                    587648.0
2                      total offences        x                   2369036.0
3               offences against life        m                      2911.0
4               offences against life        f                       586.0
...                               ...      ...                         ...
3376                              NaN      NaN                         NaN
3377                              NaN      NaN                         NaN
3378                              NaN      NaN                         NaN
3379                              NaN      NaN                         NaN
3380                              NaN      NaN                         NaN

      2015 children under 21  2015 adults 21>  ...  \
0                   398757.0        1382631.0  ...
1                   130065.0         457583.0  ...
2                   528822.0        1840214.0  ...
3                      373.0           2538.0  ...
4                       40.0            546.0  ...
...                      ...              ...  ...
3376                     NaN              NaN  ...
3377                     NaN              NaN  ...
3378                     NaN              NaN  ...
3379                     NaN              NaN  ...
3380                     NaN              NaN  ...

             2022 offence or offence category 2022 sex  \
0                              total offences        M
1                              total offences        W
2                              total offences        X
3                       offences against life        M
4                       offences against life        W
...                                       ...      ...
3376                             street crime        W
3377                             street crime        X
3378  damage to property by graffiti in total        M
3379  damage to property by graffiti in total        W
3380  damage to property by graffiti in total        X

      2022 total suspects number  2022 children under 21  2022 adults 21>  \
0                        1565240                  324371          1240869
1                         528542                  118871           409671
2                        2093782                  443242          1650540
3                           2950                     491             2459
4                            589                      49              540
...                          ...                     ...              ...
3376                       21199                    7757            13442
3377                      179744                   64726           115018
3378                        9540                    5927             3613
3379                        1372                     906              466
3380                       10912                    6833             4079

             2023 offence or offence category 2023 sex  \
0                              total offences        m
1                              total offences        f
2                              total offences        x
3                       offences against life        w
4                       offences against life        f
...                                       ...      ...
3376  damage to property by graffiti in total        f
3377  damage to property by graffiti in total        x
3378                                      NaN      NaN
3379                                      NaN      NaN
3380                                      NaN      NaN

      2023 total suspects number  2023 children under 21  2023 adults 21>
0                      1675541.0                350328.0        1325213.0
1                       571226.0                132456.0         438770.0
2                      2246767.0                482784.0        1763983.0
3                         3090.0                   520.0           2570.0
4                          645.0                    57.0            588.0
...                          ...                     ...              ...
3376                      1224.0                   759.0            465.0
3377                      9393.0                  5387.0           4006.0
3378                         NaN                     NaN              NaN
3379                         NaN                     NaN              NaN
3380                         NaN                     NaN              NaN

[3381 rows x 50 columns]>